# Travis CI configuations
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
before_install:
  - pip install --user codecov
install:
  - composer self-update
  - composer install
script:
  - vendor/bin/phpunit
after_success:
  - codecov
