$HTTP["url"] =~ "/\." {
	url.access-deny = ("")
}

$HTTP["useragent"] =~ "(Baiduspider|Yahoo! Slurp|yandex\.com/bots|TweetmemeBot|CCBot|scrapy\.org|Sogou web spider|SeznamBot|SputnikBot|kinshoobot|YisouSpider|Geohack|AhrefsBot)" {
	url.access-deny = ("result.php")
}

# This is why visiting https://refill.toolforge.org/ng/result.php works (it silently redirects to the Vue app instead of 404ing)
url.rewrite-if-not-file = (
	"^/ng/(.*)" => "/ng/index.html"
)

server.modules += ("mod_status")
status.status-url = "/server-status"
status.statistics-url = "/server-statistics"
server.max-keep-alive-requests = 30
server.max-keep-alive-idle = 5

