# Don't let randos view dotfiles
$HTTP["url"] =~ "/\." {
	url.access-deny = ("")
}

$HTTP["useragent"] =~ "(Baiduspider|Yahoo! Slurp|yandex\.com/bots|TweetmemeBot|CCBot|scrapy\.org|Sogou web spider|SeznamBot|SputnikBot|kinshoobot|YisouSpider|Geohack|AhrefsBot)" {
	url.access-deny = ("result.php")
}

# Hard-redirect the old /ng/ folder, which we don't want people to use anymore.
url.redirect = (
    "^/ng/(.*)" => "/$1",
    "^/ng$" => "/"
)

# Silently redirect everything else. This will show the Vue app for everything, instead of a 404. This ensures that legacy URLs like result.php?page=Wikipedia_talk%3AReFill&defaults=y&nowatch=y&wiki=en can be detected by the Vue router in main.js and receive special handling.
url.rewrite-if-not-file = (
	"^/(.*)" => "/index.html"
)

server.modules += ("mod_status")
status.status-url = "/server-status"
status.statistics-url = "/server-statistics"
server.max-keep-alive-requests = 30
server.max-keep-alive-idle = 5

