name: Python linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # actions/setup-python doesn't support 3.7
        python: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel setuptools
          pip install tox
          pip install -r backend/requirements.txt
      # tox is a test suite, but it's configured just to lint. see tox.ini. it lints with the libraries black and isort.
      - name: Run tox
        run: tox -v
