name: Python

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: tox
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8", "3.9", "3.10"]
        experimental: [false]
        include:
          - python: "3.11"
            experimental: true

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel setuptools
          pip install tox
          pip install -r backend/requirements.txt
      - name: Run tox
        run: tox -v
      - name: Run application
        run: python backend/app.py
