name: Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    name: tox
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel setuptools
          pip install tox
          pip install -r backend/requirements.txt
      - name: Run tox
        # Skip tox for now!
        run: tox --notest
